### ISSUE TITLE
About the implementation of rigid_icp.h

### ISSUE THREAD

**Issue by Jianxff** [hu-hy17/PhysInteraction#2]
Hi, 

I must say that the work is really great. But I wonder the implementation of `rigid_icp.h` as it is not open sourced. 

I try to implement this work with pytorch and Adam autograd, but I got stuck (works bad) of the energy functions of rigid object ($E_{dep}, E_{silh}$) and interaction ($E_{itc}, E_{tac}$) (works bad). So I want to know more details about the code implementation.

Thanks a lot,

**Comment by hu-hy17** [comment]
These energy terms are related to object shape reconstruction and pose tracking. I recommend you refer to "Dynamicfusion: Reconstruction and tracking of non-rigid scenes in real-time" for more details. 

The implementation of this part involves CUDA programming and is not open-sourced due to commercial reasons.

**Comment by Jianxff** [comment]
Thanks!
